import { Iproduct } from "./iproduct";

export let productlist:Iproduct[]=[
  {
    id:1,
    name:"Dell-XPS",
    price:500,
    quantity:0,
    image:"12.webp"
  },
  {
    id:2,
    name:"Mac",
    price:700,
    quantity:5,
    image:"2.avif"
  },
  {
    id:3,
    name:"Hp-Omen",
    price:400,
    quantity:2,
    image:"3.png"
  },
  {
    id:4,
    name:"Mac-book",
    price:650,
    quantity:65,
    image:"7.jpg"
  },
  {
    id:5,
    name:"HP",
    price:450,
    quantity:40,
    image:"1.png"
  },
  {
    id:8,
    name:"MacBook",
    price:450,
    quantity:40,
    image:"mac.jpg"
  },
  {
    id:6,
    name:"Dell",
    price:450,
    quantity:40,
    image:"dell.jpg"
  },
  {
    id:7,
    name:"Asus",
    price:450,
    quantity:40,
    image:"asus.webp"
  },
]